services:
  piper-app:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: piper-app
    restart: unless-stopped
    build: .
    ports:
      - 8630:3000
    env_file: .env # Load all variables from .env
    environment:
      # This DATABASE_URL overrides the one from .env for the Docker container
      - DATABASE_URL=postgresql://piper:piper@piper-db:5432/piper
      # Redis URL for MCP Manager
      - REDIS_URL=redis://piper-cache:6379
    volumes:
      - /mnt/cache/compose/piper/uploads:/uploads
      - /mnt/cache/compose/piper/config:/config
      - /mnt/cache/compose/piper/logs:/logs
      - /mnt/cache/compose/piper/config.json:/app/config.json
      - /mnt/user/data:/data
      - /mnt/user/code:/code
      - /mnt/user/docs:/docs
      - /mnt/user/compose:/compose
      - /mnt/user/downloads:/downloads
    command: sh -c "npx prisma migrate deploy && npm start"
    depends_on:
      - piper-db
      - piper-cache
  piper-db:
    container_name: piper-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: piper
      POSTGRES_PASSWORD: piper
      POSTGRES_DB: piper
    volumes:
      - piper-db:/var/lib/postgresql/data
    ports:
      - 8631:5432
  piper-cache:
    image: redis:alpine
    container_name: piper-cache
    ports:
      - 8632:6379
    volumes:
      - piper-cache:/data
    restart: unless-stopped
volumes:
  piper-db: null
  piper-cache: null
networks: {}
