services:
  piper-app-dev:
    container_name: piper-app-dev
    labels:
      - com.centurylinklabs.watchtower.enable=false
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Explicitly run as root
    user: "0:0"
    command: sh -c "npx prisma db push && npm run dev"
    # Expose port 3000 on host port 8630
    ports:
      - "8630:3000"
    # Load environment variables from .env file
    env_file:
      - .env
    environment:
      # Add or override any environment variables here if needed
      - NODE_ENV=development
      - DATABASE_URL=postgresql://piper:piper@piper-db-dev:5432/piper
      - REDIS_URL=redis://piper-cache-dev:6379
      # CHOKIDAR_USEPOLLING=true # Uncomment if hot reloading is unreliable
    volumes:
      # Mounts for hot reloading application code
      - .:/app
      # Isolate container's node_modules from host's
      - /app/node_modules
      # Persistent volumes for data using named volumes
      - ./uploads:/uploads
      - ./config:/config
      - ./logs:/logs
      # Other mounts you had, ensure these paths exist on your host or are appropriate for dev
      - /mnt/user/data:/data
      - /mnt/user/code:/code
      - /mnt/user/docs:/docs
      - /mnt/user/compose:/compose
      - /mnt/user/downloads:/downloads
    depends_on:
      piper-db-dev:
        condition: service_healthy
      piper-cache-dev:
        condition: service_healthy
    # Or 'no' for development if you prefer manual restarts
    restart: unless-stopped

  piper-db-dev:
    container_name: piper-db-dev
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piper"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: piper
      POSTGRES_USER: piper
      # Consider using a secret or .env for password
      POSTGRES_PASSWORD: piper
    volumes:
      - piper-db-dev:/var/lib/postgresql/data
    # Expose DB port to host, consistent with main docker-compose.yml
    ports:
      - "8631:5432"
    restart: unless-stopped

  piper-cache-dev:
    container_name: piper-cache-dev
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Expose Redis port to host, consistent with main docker-compose.yml
    ports:
      - "8632:6379"
    restart: unless-stopped
    volumes:
      - piper-cache-dev:/data

volumes:
  # Defines the named volume for PostgreSQL data persistence
  piper-db-dev:
  # Defines the named volume for Redis data persistence
  piper-cache-dev:
