// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.installation.timestamp", "133764313356095217");
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "cf38a054-2c71-49fb-9bc4-cf45797ffb59");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 4);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1740785953);
user_pref("app.update.lastUpdateTime.background-update-timer", 1740809716);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1740814922);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1740809716);
user_pref("app.update.lastUpdateTime.region-update-timer", 1740699423);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1731957922);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1740785953);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1740785953);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1740785953);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1740709632);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 1740809582);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1740785953);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{36f65e95-f809-40b0-9e7d-b45ce5a91e47}");
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", true);
user_pref("browser.ctrlTab.sortByRecentlyUsed", true);
user_pref("browser.discovery.enabled", false);
user_pref("browser.download.autohideButton", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.engagement.fxa-toolbar-menu-button.has-used", true);
user_pref("browser.firefox-view.feature-tour", "{\"screen\":\"\",\"complete\":true}");
user_pref("browser.firefox-view.view-count", 7);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1730212994);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.bookkeeping.updateAppliedTime", 1740178023);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migrate.interactions.bookmarks", true);
user_pref("browser.migrate.interactions.history", true);
user_pref("browser.migrate.interactions.passwords", true);
user_pref("browser.migration.version", 150);
user_pref("browser.ml.chat.enabled", true);
user_pref("browser.ml.chat.provider", "https://claude.ai/new");
user_pref("browser.ml.chat.shortcuts", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", true);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a41651e5-05fc-4b38-8eaf-ff25f8c9ea61}");
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.rows", 4);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 2);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"_85252760-c586-4180-8788-c50234c0ac08_\"],\"idsInUrlbar\":[\"_85252760-c586-4180-8788-c50234c0ac08_\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.protections_panel.infoMessage.seen", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1740699423);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1740815545664");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1740817350664");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1740815349478");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1740836949478");
user_pref("browser.search.region", "US");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", true);
user_pref("browser.search.totalSearches", 101);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250216192613");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1740570603");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20250216192613");
user_pref("browser.startup.homepage_override.mstone", "135.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1740570603);
user_pref("browser.startup.page", 3);
user_pref("browser.startup.windowsLaunchOnLogin.disableLaunchOnLoginPrompt", true);
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.tabs.warnOnClose",